http:
  address: :8080
  workers:
    command: "php ./vendor/bin/rr-worker"
    pool:
      numWorkers: 4

# reload can reset rr servers when files change
reload:
  # refresh internval (default 1s)
  interval: 1s
  # file extensions to watch, defaults to [.php]
  patterns: [".php"]
  # list of services to watch
  services:
    http:
      # list of dirs, "" root
      dirs: ["/app/public"]
      # include sub directories
      recursive: true
      
# стили/изображения
static:
  dir: 'public'
